#!/usr/bin/env bash
# Bash Script that displays numbers from 1 to 20 and:
#  displays "bad luck from China" on the 4th iteration
#  displays "bad luck from Japan" on the 9th iteration
#  displays "bad luck from Italy" on the 17th loop iteration

i=1

while [ $i -le 20 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy"
  esac
 (( i++ ))
done
